apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-hub-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: api-gateway-hub.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-gateway-hub-service
            port:
              number: 80
